apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-backend
  namespace: wcare-ns
  labels:
    app: wcare-application
    subname: library-app-backend
spec:
  selector:
    matchLabels:
      app: wcare-application
      subname: library-app-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: wcare-application
        subname: library-app-backend
    spec:
      containers:
        - name: container-wcareweb
          image: image-registry.openshift-image-registry.svc:5000/wcare-ns/library-app-backend:latest
          # image: "gandhicloudlab/wcareweb:latest"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 8083